repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.290
    hooks:
      # Run the linter (fix what can be fixed, warn about the rest)
      - id: ruff
        args: [ --fix, --exit-zero ]
        exclude: ^(src/.*/launch/.*\.py|tests/.*\.py)$
