# Dagger Module Configuration
[module]
name = "vehicle-navigation"
sdk = "python"
description = "CI/CD pipeline for ROS 2 Vehicle Navigation project"

[module.source]
include = ["**/*.py", "pyproject.toml", "README.md", "src/**/*", "tests/**/*"]
exclude = [
    "**/__pycache__",
    "**/*.pyc", 
    "**/build",
    "**/install", 
    "**/log",
    "**/.venv",
    "**/.git"
]
