lifecycle_manager:
  ros__parameters:
    use_sim_time: True
    autostart: true
    node_names: ['controller_server', 'smoother_server', 'planner_server', 'behavior_server', 'bt_navigator', 'waypoint_follower', 'velocity_smoother']

lifecycle_manager_localization:
  ros__parameters:
    use_sim_time: True
    autostart: true
    node_names: ['map_server', 'amcl']

lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: True
    autostart: true
    node_names: ['controller_server', 'smoother_server', 'planner_server', 'behavior_server', 'bt_navigator', 'waypoint_follower', 'velocity_smoother']
